### PR TITLE
Display error details in AWS Explorer #170

### LINKED ISSUE #170: Display error details in AWS Explorer
When errors are encountered while loading data into the AWS Explorer, relevant information needs to be shown. Currently, "No functions" is incorrectly shown.

Where possible, indicate the error code and error service in a tree node.
The tree node should show an error icon.

Consider surfacing full details (like a stack trace) - possible example: clicking on error node outputs the full details somewhere so user can copy to clipboard.

Here is a sample of the AWS Toolkit for Jetbrains
image

### PR DESCRIPTION
**Pull request by acguglielmo**
This PR fixes #170, displaying an `ErrorNode` if an exception occurs while querying AWS Resources. This new ErrorNode also has a new command that allows users to inspect and copy the stack trace.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Infrastructure (change which improves the lifecycle management (CI/CD, build, package, deploy, lint, etc) of the application, but does not change functionality.)
- [ ] Technical debt (change which improves the maintainability of the codebase, but does not change functionality)
- [x] Testing (change which modifies or adds test coverage, but does not change functionality)
- [ ] Documentation (change which modifies or adds documentation, but does not change functionality)

## Description

I have created the following new components:

- A new shared and abstract node `AWSTreeErrorHandlerNode` that is designated to create an ErrorNode as a field visible to the children classes.
- A new explorer node `ErrorNode`, that encapsulates an `Error` and is associated with a parent node.
- A new function/command `showStackTrace` that shows the details of the `Error` encapsulated in an `ErrorNode`
- A new HTML web view that displays the `Error` details.

## Motivation and Context

It will improve this extension usability by providing easy and clear access to exceptions details.

## Related Issue(s)

#170

## Testing

I did many exploratory tests and the exceptions used were exclusively related to authorization. I went many times to IAM console and changed my user's permissions. If you have other tests to recommend, please point them me out!

I also included new automated tests for the new components.

## Screenshots (if appropriate)
extension development host - error information for aws-java-simple-http-endpoint-dev update_complete - visual studio code_004

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [ ] A short description of the change has been added to the **CHANGELOG**

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/lambda/explorer/standaloneNodes.ts [hunk 1]
```diff
@@ -39,13 +40,15 @@ export class DefaultStandaloneFunctionGroupNode extends AWSTreeNodeBase implemen
         this.functionNodes = new Map<string, StandaloneFunctionNode>()
     }
 
-    public async getChildren(): Promise<StandaloneFunctionNode[]> {
-        await this.updateChildren()
+    public async getChildren(): Promise<(StandaloneFunctionNode | ErrorNode)[]> {
+        await this.handleErrorProneOperation()
 
-        return [...this.functionNodes.values()]
+        return this.errorNode ? [this.errorNode]
```
Comment (awschristou) [inline src/lambda/explorer/standaloneNodes.ts]: Everywhere you have something like this, please check `!!this.errorNode` instead of `this.errorNode`
See https://medium.com/@pddivine/javascript-bang-bang-i-shot-you-down-use-of-double-bangs-in-javascript-7c9d94446054

File: src/shared/treeview/awsTreeErrorHandlerNode.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    protected errorNode?: ErrorNode
+
+    protected constructor(
+        label: string,
+        collapsibleState?: TreeItemCollapsibleState
+    ) {
+        super(label, collapsibleState)
+    }
+
+    protected async handleErrorProneOperation() {
```
Comment (awschristou) [inline src/shared/treeview/awsTreeErrorHandlerNode.ts]: Rather than force each derived class to have only one operation that could be error handled, could this be opened up to allow arbitrary operations to be error handled? For example, an action could be passed into the function for try/catch wrapping.

**Comment by acguglielmo** [comment]
Hello @awschristou! Regarding the new SVG, I got it [here](https://en.wikipedia.org/wiki/File:Dialog-error-round.svg).

File: src/lambda/commands/showStackTrace.ts [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+        )
+
+        const baseTemplateFn = _.template(BaseTemplates.SIMPLE_HTML)
+        view.webview.html = baseTemplateFn({ content: '<h1>Loading...</h1>' })
+
+        const getConfigTemplateFn = _.template(ErrorTemplates.ERROR_INFORMATION)
+        view.webview.html = baseTemplateFn({
+            content: getConfigTemplateFn(element)
+        })
+    } catch (err) {
```
[the remark this answers is not in the document]
Comment (acguglielmo) [reply src/lambda/commands/showStackTrace.ts]: I checked the `LambdaPolicyView`. It's very well written and I believe that we can create an abstract class to handle all these kind of views with the general methods (`createView`, `dispose`, `load`, `showContent`,  `showError`, `showErrorContent` and `showLoadingContent`) and address these change in a separated PR. 

But I also saw that there is the issue #146, so I think that the above PR will not be useful at all.

What could I do for now? Could I create a small class alike `LambdaPolicyView` inside `showStackTrace.ts` just to address this UI update issue in case of error?

File: src/shared/treeview/awsTreeErrorHandlerNode.ts (hunk 2 above)
Comment (acguglielmo) [reply src/shared/treeview/awsTreeErrorHandlerNode.ts]: Good insight!

File: src/lambda/explorer/cloudFormationNodes.ts [hunk 4]
```diff
@@ -50,9 +50,11 @@ export class DefaultCloudFormationNode extends AWSTreeErrorHandlerNode implement
     }
 
     public async getChildren(): Promise<(CloudFormationStackNode | ErrorNode)[]> {
-        await this.handleErrorProneOperation()
+        await this.handleErrorProneOperation(async () => this.updateChildren(),
+                                             localize('AWS.explorerNode.cloudFormation.error',
+                                                      'Error loading Cloudformation resources'))
```
Comment (awschristou) [inline src/lambda/explorer/cloudFormationNodes.ts]: `Cloudformation` -> `CloudFormation`

File: src/lambda/commands/showStackTrace.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (awschristou) [reply src/lambda/commands/showStackTrace.ts]: #146 is outdated. If you're interested in making a reusable class as mentioned in a separate PR, that sounds great. I think for this PR, the catch can replace the webview text with the error message as a simple way of wrapping up this PR.

File: src/lambda/commands/showErrorDetails.ts [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+export async function showErrorDetails(element: ErrorNode) {
+    const view = vscode.window.createWebviewPanel(
+        'html',
+        `Error details for ${element.parent.label}`,
+        -1
+    )
+
+    try {
+        const baseTemplateFn = _.template(BaseTemplates.SIMPLE_HTML)
+        view.webview.html = baseTemplateFn({ content: '<h1>Loading...</h1>' })
```
Comment (mpiroc) [inline src/lambda/commands/showErrorDetails.ts]: `Loading...` should be localized, i.e.:

```typescript
content: `<h1>${_.esacpe(localize('myLocId', 'Loading...')}</h1>`
```

File: src/lambda/explorer/cloudFormationNodes.ts [hunk 6]
```diff
@@ -48,13 +49,17 @@ export class DefaultCloudFormationNode extends AWSTreeNodeBase implements CloudF
         this.stackNodes = new Map<string, CloudFormationStackNode>()
     }
 
-    public async getChildren(): Promise<CloudFormationStackNode[]> {
-        await this.updateChildren()
+    public async getChildren(): Promise<(CloudFormationStackNode | ErrorNode)[]> {
+        await this.handleErrorProneOperation(async () => this.updateChildren(),
```
Comment (mpiroc) [inline src/lambda/explorer/cloudFormationNodes.ts]: Style nit: When splitting arguments into multiple lines, we indent each a single level. For example:

```typescript
await this.handleErrorProneOperation(
    async () => this.updateChildren(),
    localize(
        'AWS.explorerNode.cloudFormation.error',
        'Error loading CloudFormation resources'
    )
)
```

File: src/lambda/templates/errorTemplates.ts [hunk 7]
```diff
@@ -0,0 +1,34 @@
+/*!
+ * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+export class ErrorTemplates {
+    public static readonly SHOW_ERROR_DETAILS = `
+    <h1>
+        Error details for <%= parent.label %>
```
Comment (mpiroc) [inline src/lambda/templates/errorTemplates.ts]: Any English text needs to be localized, so the entire text `Error details for {0}` should be localized.

The same applies for `Error code`, `Error message`, and `Stack trace`.

File: src/test/lambda/explorer/cloudFormationNodes.test.ts [hunk 8]
```diff
@@ -194,34 +194,32 @@ describe('DefaultCloudFormationStackNode', () => {
...
 
-        const fileScheme: string = 'file'
-        const resourceImageName: string = 'cloudformation.svg'
+describe('DefaultCloudFormationNode', () => {
 
-        const testNode = new DefaultCloudFormationStackNode(
-            new DefaultCloudFormationNode(new DefaultRegionNode(new RegionInfo('code', 'name'))),
-            fakeStackSummary
-        )
+    it('handle error', async () => {
```
Comment (mpiroc) [inline src/test/lambda/explorer/cloudFormationNodes.test.ts]: `'handles errors'`

File: src/test/lambda/explorer/standaloneNodes.test.ts [hunk 9]
```diff
@@ -101,3 +102,28 @@ describe('DefaultStandaloneFunctionNode', () => {
...
+        ) {
+            super(parent)
+        }
+
+        public async updateChildren(): Promise<void> {
+            throw new Error('Hello there!')
+        }
+    }
+
+    it('handle error', async () => {
```
Comment (mpiroc) [inline src/test/lambda/explorer/standaloneNodes.test.ts]: `'handles errors'`

**Comment by acguglielmo** [comment]
Hello @mpiroc! Thanks for your feedback. I addressed your requested changes with a new commit. Please check if everything is in place this time!
